#!/bin/bash

trbcmd w $TDC 0xd417 0xFFFFFFFF # disable all CS lines, invert all CS lines to get a zero on all lines
sleep 0.2
trbcmd w $TDC 0xd417 0x0000FFFF # disable all CS lines, invert all CS lines to get a one on all lines, reset complete

